// <auto-generated />
using System;
using GeekSeatWitchSaga.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekSeatWitchSaga.Data.Migrations
{
    [DbContext(typeof(GeekSeatWitchSagaContext))]
    [Migration("20220724141410_UpdateModel")]
    partial class UpdateModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("GeekSeatWitchSaga.Models.Villager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AgeOfDeath")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberKilled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearKilled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearOfDeath")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Villager");
                });
#pragma warning restore 612, 618
        }
    }
}
